repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: check-toml
    - id: check-yaml
    - id: debug-statements
    - id: check-merge-conflict
    - id: check-json
    - id: end-of-file-fixer
- repo: https://github.com/timothycrosley/isort
  rev: 5.10.1
  hooks:
    - id: isort
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
    - id: black
- repo: https://github.com/asottile/blacken-docs
  rev: v1.12.1
  hooks:
    - id: blacken-docs
      additional_dependencies: ["black==21.12b0"]
- repo: local
  hooks:
    - id: flakehell
      name: flakehell
      entry: flakehell
      args: [lint]
      language: python
      types: [python]
      require_serial: true
      additional_dependencies: [
        'flake8~=3.9.2',
        'flakehell~=0.9.0',
        'flake8-builtins~=1.5.3',
        'flake8-blind-except~=0.2.0',
        'flake8-logging-format~=0.6.0',
        'flake8-bugbear~=21.9.2',
        'flake8-annotations~=2.6.2',
        'flake8-docstrings~=1.6.0',
        'flake8-bandit~=2.1.2',
        'darglint~=1.8.0'
      ]
- repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
  hooks:
  -   id: fmt
  -   id: clippy
      args:
        - --release
        - --
        - -D
        - warnings
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.2.3
  hooks:
    - id: nbqa-isort
    - id: nbqa-black
