repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-toml
    - id: check-yaml
    - id: debug-statements
    - id: check-merge-conflict
    - id: check-json
    - id: end-of-file-fixer
- repo: https://github.com/timothycrosley/isort
  rev: 5.11.4
  hooks:
    - id: isort
- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
    - id: black
- repo: https://github.com/asottile/blacken-docs
  rev: v1.12.1
  hooks:
    - id: blacken-docs
      additional_dependencies: ["black==22.3.0"]
- repo: local
  hooks:
    - id: flakeheaven
      name: flakeheaven
      entry: flakeheaven
      args: [lint]
      language: python
      types: [python]
      require_serial: true
      additional_dependencies: [
          "flake8~=4.0",  # Don't upgrade, because flake8 5.0 is incompatible with flakeheaven
          "flakeheaven==3.0.0",
          "flake8-builtins",
          "flake8-blind-except",
          "flake8-logging-format",
          "flake8-bugbear",
          "flake8-annotations",
          "flake8-docstrings",
          "flake8-bandit",
      ]
- repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
  hooks:
   - id: fmt
   - id: clippy
     args:
       - --release
       - --
       - -D
       - warnings
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.5.3
  hooks:
    - id: nbqa-isort
    - id: nbqa-black
