version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
    rust: "1.55"

formats: all

sphinx:
  configuration: docs/conf.py

python:
  version: 3.9
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
