[package]
name = "narrow_down"
version = "0.2.0"
edition = "2021"

[package.metadata.maturin]
name = "narrow_down._rust"

[lib]
name = "narrow_down"
path = "rust/lib.rs"
crate-type = ["cdylib"]

[dependencies]
twox-hash = "1.6.2"
mur3 = "0.1.0"
numpy = "0.15.0"
pyo3 = { version = "0.15.1", features = ["extension-module", "abi3-py37"] }
