line-length = 100
extend-exclude = ["*.ipynb", "**/*_pb2.py", "**/*_pb2.pyi"]
select = [
    "A",  # flake8-builtins
    "C4",  # flake8-comprehensions
    "DTZ",  # flake8-datetimez
    "B",
    "B9",
    "C",
    "G",  # flake8-logging-format
    "PYI",  # flake8-pyi
    "PT",  # flake8-pytest-style
    "TCH",  #  flake8-type-checking
    "C90",  # MCCabe
    "D",  # Pydocstyle
    "E",  # Pycodestyle error
    "F",  # Pyflakes
    "I",  # Isort
    "N",  # pep8-naming
    "W",  # Pycodestyle warning
#    "ANN",  # flake8-annotations
    "S",  # flake8-bandit
    "BLE",  # flake8-blind-except
    "PD",  # pandas-vet
    "PL",  # Pylint
    "RUF",  # Ruff
]
ignore = ["C408", "PLR0913", "S608", "PYI021"]

[mccabe]
max-complexity = 18

[pydocstyle]
convention = "google"

[per-file-ignores]
"__init__.py" = ["F401"]
"tests/*" = ["ANN", "D", "S101", "PT", "PLR", "PD901", "RUF001"]
"integration_tests/*" = ["ANN", "D", "S101", "PT", "PLR", "PD901", "RUF001"]
