# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: proto/stored_document.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class StoredDocumentProto(betterproto.Message):
    """
    StoredDocumentProto is a protobuf representation of
    narrow_down.data_types.StoredDocument
    """

    id_: int = betterproto.uint64_field(1)
    document: str = betterproto.string_field(2)
    exact_part: str = betterproto.string_field(3)
    fingerprint: List[int] = betterproto.uint32_field(4)
    data: str = betterproto.string_field(5)
