name: publish-docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          architecture: x64
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml
            Cargo.toml
            Cargo.lock

      - name: Intall pip maturin invoke
        run: |
          python3 -m pip install --upgrade pip maturin invoke

      - name: Install project
        run: |
          pip install -e .[scylladb,docs]

      - run: inv docs

      - name: Deploy
        if: "github.event_name != 'pull_request'"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build
