name: publish-docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          architecture: x64
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml
            Cargo.toml
            Cargo.lock

      - name: Install Protoc
      uses: arduino/setup-protoc@v1

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Intall pip maturin
        run: |
          python3 -m pip install --upgrade pip maturin

      - name: Install project
        run: |
          pip install -e .[scylladb,docs]

      - run: task docs

      - name: Deploy
        if: "github.event_name != 'pull_request'"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build
